### ISSUE TITLE
Update the readme to explain what this is, and why someone would want to use it

### ISSUE THREAD

**Issue by samlh** [DefenSec/dssp#38]

**Comment by doverride** [comment]
Thanks for the suggestion!

How about the the following:

https://github.com/DefenSec/dssp/commit/a78a35d264fe4a1c645a74a5e43854c6485e7102

**Comment by doverride** [comment]
It is a work in progress. Best to look at the current revision:

https://github.com/DefenSec/dssp/blob/master/README.md

**Comment by samlh** [comment]
Thank you for the explanation, much appreciated!
